package com.example.FruitTrees.WeatherProcessor.WeatherProcessors.Observation;

import com.example.FruitTrees.Location.Location;

/**
 * Run-scoped context object for a single weather calculation execution.
 *
 * One WeatherRunContext represents:
 *  - exactly one location
 *  - exactly one calculation version (algorithm epoch)
 *  - exactly one collection of produced observations
 *
 * It is created by the orchestration layer (service) and passed to all
 * weather processors involved in the run. Processors use it to:
 *  - know which location they are computing for
 *  - publish their results into the shared ObservationCollector
 *  - tag results with the calculation version for reproducibility
 *
 * This object is NOT serialized to clients. It is internal plumbing that
 * ties together processors, collectors, and exporters for one run.
 */
public record WeatherRunContext(

        /**
         * Full geographic and human-readable description of the location
         * being processed (city, state, county, latitude, longitude, etc.).
         * Serves as contextual metadata; the stable identity is location.getId().
         */
        Location location,

        /**
         * Run-scoped collector that receives all Observation records
         * generated by processors during this execution.
         */
        ObservationCollector collector,

        /**
         * Version of the scientific calculation logic used to produce
         * the observations in this run. This changes only when the
         * underlying algorithms or thresholds change, not when UI or
         * infrastructure code is modified.
         */
        int calcVersion
) {
    /**
     * Convenience accessor for the stable internal location identifier.
     * This is what is stored in each Observation for joins and comparisons.
     */
    public String locationId() {
        return location.getId();
    }
}
